In [1]:
import numpy as np

In [5]:
arr=np.arange(9)
arr,arr.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), (9,))

In [10]:
arr2=arr.reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
flattened=arr2.flatten()
flattened[0]=34
flattened

array([34,  1,  2,  3,  4,  5,  6,  7,  8])

In [15]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
flattened=arr2.ravel()
flattened[0]=234
flattened

array([234,   1,   2,   3,   4,   5,   6,   7,   8])

In [17]:
arr2

array([[234,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

In [18]:
# ravel don't create new array, so memory efficient,
# flatten doesn't affect one