In [1]:
# creation
import numpy as np
arr=np.array([1,2,3,4,5])

In [2]:
arr.ndim

1

In [3]:
arr.shape

(5,)

In [4]:
arr.size

5

In [5]:
arr.dtype

dtype('int64')

In [6]:
arr.astype(float)

array([1., 2., 3., 4., 5.])

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr.itemsize

8

In [9]:
# total memory
arr.size*arr.itemsize

40

In [17]:
np.arange(10),np.arange(1,10,2),np.linspace(1,102,5,dtype=int)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 3, 5, 7, 9]),
 array([  1,  26,  51,  76, 102]))