In [ ]:
# https://github.com/Devinterview-io/numpy-interview-questions

In [10]:
# Broadcasting

In [11]:
import numpy as np

In [12]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1.shape,arr2.shape)
arr1+arr2

(3,) (3,)


array([5, 7, 9])

In [13]:
arr1+4

array([5, 6, 7])

In [14]:
arr1=np.array([1,2,3]) # becomes
# [[1,2,3]
#  [1,2,3]
#  [1,2,3]]
arr2=np.array([[4],
               [5],
               [6]])
# [[4,4,4],
#  [5,5,5],
#  [6,6,6]]
arr1+arr2

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [15]:
# failing condition
arr1=np.array([1,2,3])
print(arr1.shape)
arr2=np.array([4,5,6,7])
print(arr2.shape)

arr1+arr2
# rules are from right to left the axis should be either equal or 1, here this condition failing 3!=4 and there is no 1


(3,)
(4,)


ValueError: operands could not be broadcast together with shapes (3,) (4,) 