In [6]:
import numpy as np
arr=np.arange(100).reshape((10,10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [7]:
arr[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[0][1]

np.int64(1)

In [9]:
arr[0,1] # arr[0][1] both are same

np.int64(1)

In [11]:
arr[3,4] # 4th row, 5 col

np.int64(34)

In [12]:
# slicing

In [13]:
arr[0:3,]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [15]:
arr[:,0:3] # all rows and specific columns

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42],
       [50, 51, 52],
       [60, 61, 62],
       [70, 71, 72],
       [80, 81, 82],
       [90, 91, 92]])

In [16]:
# what if step size need to increase from 1
arr[::2,::3]

array([[ 0,  3,  6,  9],
       [20, 23, 26, 29],
       [40, 43, 46, 49],
       [60, 63, 66, 69],
       [80, 83, 86, 89]])

In [18]:
# Note:
# if i specified indexes in array

arr[(0,3),(4,5)]

array([ 4, 35])

In [19]:
arr[[(0,3),(4,5)]]


array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]])