In [1]:
# Randomgen

In [2]:
import numpy as np
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [3]:
arr_rg=gen(pcg(seed=99))
arr_rg

Generator(PCG64) at 0x24F2E83C4A0

In [5]:
arr_rg=gen(pcg(seed=99))
arr_rg.normal(size=(5,5))

array([[ 0.0824943 , -0.46441841,  0.05051506,  0.68623082, -1.75679051],
       [ 1.6844316 , -0.45784284, -0.59642009, -1.04696756,  0.93179202],
       [ 0.67498048,  1.2444412 ,  0.89308742,  0.26300494,  0.32851785],
       [ 0.93524369, -0.87761299, -0.04589609,  0.38187174, -0.45253897],
       [ 0.72166488, -0.35216341,  0.67279702,  0.14062329,  0.46256068]])

In [6]:
arr_rg=gen(pcg(seed=99))
arr_rg.integers(low=10,high=20,size=(5,5))

array([[19, 15, 17, 15, 11],
       [15, 19, 19, 19, 16],
       [13, 15, 16, 12, 19],
       [15, 13, 14, 11, 16],
       [13, 19, 13, 12, 16]])

In [10]:
arr_rg=gen(pcg(seed=99))
arr_rg.random(size=(5,5))

array([[0.50603067, 0.56509163, 0.51191596, 0.97218637, 0.61490314],
       [0.5682835 , 0.28678672, 0.55451145, 0.46752353, 0.61005801],
       [0.9304425 , 0.24588538, 0.30943834, 0.39107965, 0.27027173],
       [0.35001495, 0.93622969, 0.37788422, 0.77464921, 0.04056724],
       [0.2986556 , 0.70259115, 0.45225262, 0.88985789, 0.43510003]])

In [12]:
import numpy as np
np.random.rand(10)

array([0.41693346, 0.38817499, 0.64145463, 0.90596368, 0.92486633,
       0.52551016, 0.92991567, 0.18948872, 0.93301791, 0.28003146])

In [16]:
np.random.randn(10)

array([ 0.15186487,  0.44233328, -0.30029084, -0.46112257,  0.82923822,
       -1.25627572, -0.8082938 , -1.68880656, -0.54951591,  1.95118931])

In [18]:
np.random.randint(1,10,(5,5))

array([[6, 6, 8, 9, 5],
       [3, 6, 4, 9, 9],
       [7, 4, 2, 4, 9],
       [8, 7, 9, 9, 1],
       [4, 7, 4, 4, 9]], dtype=int32)

In [21]:
np.random.choice(np.array([4,5,6,20]),(4,5))

array([[ 6,  4,  5,  4,  5],
       [ 5, 20,  4,  4,  6],
       [ 5,  6,  6, 20,  5],
       [ 6,  4,  5, 20,  4]])

In [23]:
a=np.array([1,2,3,4,5])
np.random.shuffle(a)
a

array([3, 2, 5, 4, 1])

In [24]:
'''
Normal random disadv
------------------------------------------
Random Generators (Why Use Them)
Legacy np.random.* uses a global state, causing issues in multithreading or parallel code where calls interfere. np.random.Generator (via default_rng()) fixes this:

Thread-safe: Each generator has independent state, avoiding race conditions.
Reproducible: Seed once per generator: rng = np.random.default_rng(42). Same seed yields identical sequences across runs.
Faster PCG64: Default algorithm outperforms older Mersenne Twister for vectorized operations.
Controlled streams: Create multiple generators for separate tasks without global state pollution.
'''

'\nNormal random disadv\n------------------------------------------\nRandom Generators (Why Use Them)\nLegacy np.random.* uses a global state, causing issues in multithreading or parallel code where calls interfere. np.random.Generator (via default_rng()) fixes this:\n\nThread-safe: Each generator has independent state, avoiding race conditions.\nReproducible: Seed once per generator: rng = np.random.default_rng(42). Same seed yields identical sequences across runs.\nFaster PCG64: Default algorithm outperforms older Mersenne Twister for vectorized operations.\nControlled streams: Create multiple generators for separate tasks without global state pollution.\n'

In [25]:
import numpy as np
rng = np.random.default_rng(42)  # Seeded generator
print(rng.random(3))  # [0.773956, 0.643865, 0.177394]
print(rng.integers(0, 10, 3))   # Controlled integers


[0.77395605 0.43887844 0.85859792]
[0 6 2]
